<?php
    namespace Bearlovescode\Taxonomy\Providers;

    use Illuminate\Support\ServiceProvider;

    class TaxonomyServiceProvider extends ServiceProvider
    {
        public function boot() {}

        public function register(): void
        {
            parent::register(); // TODO: Change the autogenerated stub

            $this->setupMigrations();
            $this->setupViews();
        }

        private function setupMigrations(): void
        {
            $this->loadMigrationsFrom([
                __DIR__ . '/../../database/migrations'
            ]);
        }

        private function setupViews(): void
        {
            $this->loadViewsFrom([
                __DIR__ . '../../resources/views'
            ], 'taxonomy');

            $this->publishes([
                __DIR__ . '../../resources/views' => resource_path('views/vendor/taxonomy')
            ], 'views');
        }
    }