<?php
    namespace Bearlovescode\Taxonomy\Providers;

    use Illuminate\Support\ServiceProvider;

    class TaxonomyServiceProvider extends ServiceProvider
    {
        public function boot() {}

        public function register(): void
        {
            parent::register(); // TODO: Change the autogenerated stub

            $this->loadMigrationsFrom([
                __DIR__ . '/../../database/migrations'
            ]);
        }
    }