<?php
    namespace Bearlovescode\Taxonomy\Providers;

    use Illuminate\Support\ServiceProvider;

    class TaxonomyServiceProvider extends ServiceProvider
    {
        public function boot() {}

        public function register()
        {
            parent::register(); // TODO: Change the autogenerated stub

            $this->loadMigrationsFrom([
                '../../database/migrations'
            ]);
        }
    }